version: '3.4'

services:
  solaxmqttbridge:
    image: ${DOCKER_REGISTRY-}solaxmqttbridge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2901:2901
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=pv
      - MQTT_DISCOVERY_PREFIX=homeassistant
    volumes:   
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: on-failure
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto_config:/mosquitto/config

